<?php

/**
 * This is the model base class for the table "task_attachment".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "TaskAttachment".
 *
 * Columns in table "task_attachment" available as properties of the model,
 * and there are no model relations.
 *
 * @property string $id
 * @property string $task_id
 * @property string $path
 * @property string $name
 *
 */
abstract class BaseTaskAttachment extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'task_attachment';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'TaskAttachment|TaskAttachments', $n);
	}

	public static function representingColumn() {
		return 'path';
	}

	public function rules() {
		return array(
			array('task_id', 'required'),
			array('task_id', 'length', 'max'=>11),
			array('path', 'length', 'max'=>400),
			array('name', 'length', 'max'=>255),
			array('path, name', 'default', 'setOnEmpty' => true, 'value' => null),
			array('id, task_id, path, name', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'id' => Yii::t('app', 'ID'),
			'task_id' => Yii::t('app', 'Task'),
			'path' => Yii::t('app', 'Path'),
			'name' => Yii::t('app', 'Name'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('id', $this->id, true);
		$criteria->compare('task_id', $this->task_id, true);
		$criteria->compare('path', $this->path, true);
		$criteria->compare('name', $this->name, true);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}